version: "1.0"
services:
    superhero-api:
        image: superhero-api
        container_name: superhero-app
        ports:
            - "5000:80"
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: db
        ports:
            - "1433:1433"
        environment: 
            - ACCEPT_EULA=y
            - SA_PASSWORD=P@ssw0rd2024