name: Publish 🚀

on: 
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./Superhero.sln

      - name: Build
        run: dotnet build ./Superhero.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ./Superhero.sln --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./Superhero.sln --configuration Release --no-build
        
        
